runtime: python27
api_version: 1
threadsafe: true

env_variables: 
    GAE_USE_CTYPES: '1'

handlers:
- url: /
  script: main.app
  
- url: /RegisterNAO/
  script: main.app
  
- url: /RegisterNAO/(.*)/
  script: main.app
  
 - url: /RegisterNAO/(.*)/Delete/
  script: main.app
